Update variable declarations to use ES6 style as suggested in #29
savoirfairelinux/ringme.js pull request #33
Opened 2017-10-05 20:48 UTC by nabrahamson

## Fixes #29 by @nabrahamson

### Changes proposed in this pull request:

* Updated variable and function declarations to use let or const. 
* const was used in cases where a function was being declared or the variable
   appeared to be immutable.  
* let was used for all others.

### Status

- [ ] READY
- [ ] HOLD
- [X] WIP (Work-In-Progress)

### How to verify this change

Verify that the variable name changes are to your liking.  

### Additional notes

The test web page will not load properly until you have an ES6 compiler (Babel / Webpack) implemented for this project.

I would reccomend further work to change function declaration to use the
syntax:
  "function foo(arg1, arg2) { }"

And the main function should be exported by:
  "export default function Ringme() {
   ...
   }"

2017-10-06 02:24 UTC, samnegri requested changes
I think maybe you misunderstood the use of `const` ou maybe I'm missing something here. `const` identifier means that you can assign the value of the variable only once, but you can change the values or contents within the variable. Consider checking [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const)

2017-10-06 02:24 UTC, samnegri commented on src/ringme.js
> -  var _launchUri = function(uri, successCallback, noHandlerCallback, unknownCallback) {
There's a syntax error here, it is missing the attribution and the `function` keyword. This should be something like
```
const _lauchUri = function(uri, successCallback, noHandlerCallback, unknownCallback) {
```

2017-10-06 02:24 UTC, samnegri commented on src/ringme.js
> -    var ui;
Why not use `const` here?

2017-10-06 02:24 UTC, samnegri commented on src/ringme.js
> -    var img = document.createElement('img');
Why not use `const` here?

2017-10-06 02:24 UTC, samnegri commented on src/ringme.js
> -    var anchor = document.createElement('a');
Why not use `const` here?

2017-10-06 02:24 UTC, samnegri commented on src/ringme.js
> -      var redirect = confirm(
Why not use `const` here?

2017-10-08 18:47 UTC, ssirois commented
I have manually merge #43 in order to add credit where it belonged in this team effort.

Thanks to @samnegri, @nabrahamson and @combmag for all the work that gave us the possibility to close this issue rapidly and efficiently.

I will close this PR that have been deprecated by this manual push.

![image](https://user-images.githubusercontent.com/747926/31319792-3fde0632-ac37-11e7-8c0e-97ebfafee942.png)

2017-10-08 18:47 UTC, closed without merging